### ISSUE TITLE
"uninitialized const member 'PinLookup::*'" errors

### ISSUE THREAD

**Issue by alexchumak** [ocrdu/Arduino_SAMD21_turbo_PWM#3] opened 2020-06-24 01:14 UTC
I had to remove the "const" prefix from the definition in the header file for it to compile. Am I missing something?

```
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::port'
 };
 ^
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::samd21Pin'
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::timer'
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::pMux'
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::port'
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::samd21Pin'
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::timer'
~/Documents/Arduino/libraries/SAMD21_turbo_PWM/src/SAMD21turboPWM.h:112:1: error: uninitialized const member 'PinLookup::pMux'
```

**Comment by ocrdu** [comment] 2020-07-27 17:05
Hi,

I don't know why that happens; many parts of C++ are dark an dangerous to me. Only thing I can think of is that your compiler is set to a more pedantic mode than mine. I haven't heard about this from other users (yet).

I don't initialise everything in the lookup tables in the header file, only what is used; maybe that is the problem, combined with compiler settings.

I t does work properly for you, after your fix?

**Comment by jwestmoreland** [comment] 2020-08-30 07:09
Hello @ocrdu ,

Actually, in your PinLookup struct - arduinoPin should be declared:

const int arduinoPin;        // Arduino pin number

since you're using -1's as initializers for undefined lines.

That cleared it up for me - otherwise I couldn't compile.

Thanks,
John W.

**Comment by ocrdu** [comment] 2020-08-30 08:20
Thanks! I fixed that, and got rid of some compiler warnings as well, in version 0.8.0. Let me know if that has worked for you.

I wonder why 0.7.0 it did compile for me and some others; consider this I must.

**Comment by ocrdu** [comment] 2020-08-30 08:20
Thanks! I fixed that, and got rid of some compiler warnings as well, in version 0.8.0. Let me know if that has worked for you.

I wonder why 0.7.0 it did compile for me and some others; consider this I must.

**Comment by jwestmoreland** [comment] 2020-08-30 08:42
Hello @ocrdu ,

Version 0.8.0 built fine for me.

Which version of the tools are you building with?

This is the latest I have from Arduino:

\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++

Thanks,
John W.

**Comment by ocrdu** [comment] 2020-08-30 09:28
Hi @jwestmoreland,

That is the same one I have and use. I would have expected the compiler to yell at me and call me names, but no. Oh well, it's fixed now.

**Comment by ocrdu** [comment] 2020-08-30 09:31
Hi @alexchumak,

I could reproduce the errors you show as warnings only, which is a bit surprising, but I think I have fixed things in version 0.8.0. Please let me know if that works for you.

**Comment by jwestmoreland** [comment] 2020-08-30 11:41
Hello @ocrdu ,

You can promote warnings to errors in compiler directives; but I don't know how you'd demote an error to a warning - that's typically not possible - at least I think (unless you're running an experimental version of a compiler).

Maybe check the [GNU reference.](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)

Just so you know - I'm using your lib over [here:](https://github.com/jwestmoreland/LedDisplay)

Thanks,
John W.

**Comment by ocrdu** [comment] 2020-08-31 11:09
Hi @jwestmoreland,

Can't test your code for want of that display, but it should be able to make smoother transistions in brightness, especially if you want to "pulse" the display.

**Comment by jwestmoreland** [comment] 2020-09-01 06:40
Hello @ocrdu ,

Tested and works OK - definitely gives more control over brightness than the default method (setting 4 bit value).

Thanks!
John W.

**Closed as completed** 2020-09-01 10:29 UTC
Labels: bug
